# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI CD BKD

on:
  push:
    branches: ["main"]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20]
    env:
      NEXT_PUBLIC_API_URL: https://bkd.newus.id/api
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name : Run NPM
      run: npm ci
    - name : Run build
      run: npm run build --if-present
    - name : restart PM2
      run : |
          APP_NAME="bkd.newus.id"
          APP_ID="17"
          if pm2 restart $APP_NAME; then
            echo "Successfully restarted app with name $APP_NAME"
          else
            echo "Failed to restart app with name $APP_NAME, trying with ID $APP_ID"
            if pm2 restart $APP_ID; then
              echo "Successfully restarted app with ID $APP_ID"
            else
              echo "Failed to restart app with both name and ID"
              exit 1
            fi
          fi
